### ISSUE TITLE
 java.lang.NullPointerException: null cannot be cast to non-null type android.location.LocationManager

### ISSUE THREAD

**Issue by NadeemKhanFh** [Richou/react-native-android-location-enabler#107]
Caused by java.lang.NullPointerException: null cannot be cast to non-null type android.location.LocationManager
       at com.heanoria.library.reactnative.locationenabler.AndroidLocationEnablerModule.isLocationProviderEnabled(AndroidLocationEnablerModule.kt:121)
       at com.heanoria.library.reactnative.locationenabler.AndroidLocationEnablerModule.onActivityResult(AndroidLocationEnablerModule.kt:132)
       at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:393)
       at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:824)
       at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:187)
       at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:151)
       at expo.modules.ReactActivityDelegateWrapper.onActivityResult(ReactActivityDelegateWrapper.kt:241)
       at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:75)
       at android.app.Activity.dispatchActivityResult(Activity.java:9362)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:6056)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:6102)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8919)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by VJ-GURU** [comment]
Hello @Richou experiencing the same issue while calling promptForEnableLocationIfNeeded();
Could you please take a look ?

**Comment by XI4636-Drakshayani** [comment]
Hello @Richou  Facing the same issue. Please take a look into it

**Comment by Richou** [comment]
Hi @XI4636-Drakshayani, what version of this library and package `com.google.android.gms:play-services-location` do you use ?

**Comment by XI4636-Drakshayani** [comment]
> Hi [@XI4636-Drakshayani](https://github.com/XI4636-Drakshayani), what version of this library and package `com.google.android.gms:play-services-location` do you use ?

@Richou  We are using 
play-services-location >> 21.0.1
react-native-android-location-enabler >> 2.0.1

**Comment by Richou** [comment]
@XI4636-Drakshayani Can you try to update the version of `react-native-android-location-enabler` to `3.0.1` and see if that fixed your issue ?
